### ISSUE TITLE
Ha lansert eksisterende kalkulator-side på v3.variant.no

### ISSUE THREAD

**Issue by mikaelbr** [varianter/variant.no#476]
Dekker ikke:
- Ikke koblet til Sanity for selve kalkulator-modellen
- Ikke støtte for Svensk modeller
- Ikke med ferdig design, men tilrettelagt for implementasjon av ny profil når det er klart.

⚠  Det som i dagens løsning, under "goder", er dynamisk, avventer vi med med tanke på UU. Vi tar en prat med Julia.

Sitte med:
- Eksisterende kalkulator-siden lansert under v3
- Tekst og goder styrt av CMS

```[tasklist]
### Tasks
- [ ] https://github.com/varianter/variant.no/issues/481
- [ ] https://github.com/varianter/variant.no/issues/483
- [ ] https://github.com/varianter/variant.no/issues/486
- [ ] https://github.com/varianter/variant.no/issues/490
- [ ] https://github.com/varianter/variant.no/issues/488
- [ ] https://github.com/varianter/variant.no/issues/497
- [ ] https://github.com/varianter/variant.no/issues/493
- [ ] https://github.com/varianter/variant.no/issues/498
- [ ] https://github.com/varianter/variant.no/issues/523
```

1: I sanity:
- Oppretter SalaryAndBenefits side:
- - Oppretter Benefits schema, som er et array
- - - Opprett Benefit schema type

2: I sanity: 
- Referert til SalaryAndBenefits i link.tsx

I web:
3:  rendre SalaryAndBenefit dersom den har blitt lagt til i nav eller _type == 'salaryAndBenefits'
- return Kalkulator i SalaryAndBenefits
- return Benefits i SalaryAndBenefits

(før sanity er ferdig så kan men rendre på mock-path /kalkulator)
1: Kalkulator fra main inn i v3
- - Form for kalkulator (input + radiobutton group)
- - Business logic + utregning

**Comment by christinaroise** [comment]
Etter teknisk prat har vi bestemt at:
- dynamisk data relatert til kalkulator (spesifikt lønn) skal inn i Sanity. (Vi har Sverige i tankene, men justerer for Norge per nå — inntil videre)


Resten av kalkulator siden settes på vent til vi vet mer. Det må avklares med Rekruttering + Sverige
