### ISSUE TITLE
Ha justert eksisterende løsning for felles innhold

### ISSUE THREAD

**Issue by christinaroise** [varianter/variant.no#521]
- rename pages til dynamic pages
- flytte blog + salary under static pages
- kommentere bort posts fra parent project
```[tasklist]
### Tasks
- [x] Rename "pages" to "Dynamic pages"
- [x] Move blog and salary under "static pages"
- [x] Comment out post from parent project
- [ ] Add custom button to shared studio within static pages in studio that shares content (blog, costumer cases i.e)
```
