### ISSUE TITLE
Kalkulator skal være tilgjengelig på gitt URL og innhold skal være styrt fra CMS

### ISSUE THREAD

**Issue by anemne** [varianter/variant.no#541]
## Bakgrunn og behov

Kalkulator er en av de mest besøkte sidene. Men den blir fort statisk og vanskelig å oppdatere. Så i overgang til CMS burde vi kunne justere på mye via CMS for å holde goder, vilkår og lønn oppdatert og spisse budskap etterhvert som vi lærer mer om hva slags informasjon folk er interessert i.

Målet med denne er å flytte datagrunnlaget. Visuell utforming går ikke inn i oppgaven. Vi kan vise kun tekst uten noe form for styling som output.

Det foregår innsiktsarbeid som finner ut bedre hva slags informasjon mulige søkere er interessert i, men inntil vi har en konklusjon der er det fint å ta utgangspunkt i det vi har:

- Lønn (kalkulatoren) som viser lønn basert på erfaring.
- Vise historisk utvikling av bonus.
- Vise pensjon og fremheve hvordan pensjon er viktig.
- Synliggjøre andre goder som er viktige:
  - Kompetansebygging (konferanser, innkjøp av ting, kurs, etc)
  - Fri i jula
  - Variantdager (1 dag i mnd)
  - Variantturer
  - Gadgetbudsjett
  - Treningsbudsjett
  - osv

Disse siste godene bør være fleksible og kunne endres både i rekkefølge, innhold og ordlyd.
Datagrunnlag burde kunne settes for lønn basert på erfaring, pensjonsordrning og bonus (basert på selskap/kontor).

## Fremtidige behov

Her er behov som vil kunne løses, men som kan scopes ut i første runde (utsettes)
- Kalkulatoren burde kunne inkluderes på svenske sider og norske sider.
- Det vil kunne være behov for å synliggjøre egne løsninger for enkelte byer. Men dette må ikke løses som en del av første leveranser.

## Akseptansekriterier

- [x] Endring av vilkår og goder skal dukke opp på nettsiden etter lagring i CMS.
- [x] Skal være mulig å endre rekkefølgen på vilkår og goder.
- [x] Alt innhold som er vist i dagens /kalkulator er dekt i ny kalkulator
- [ ] Løsningen følger vanlige WCAG 2.1-krav

```[tasklist]
### Tasks
- [ ] https://github.com/varianter/variant.no/issues/545
- [ ] https://github.com/varianter/variant.no/issues/544
- [ ] https://github.com/varianter/variant.no/issues/543
- [ ] https://github.com/varianter/variant.no/issues/547
- [ ] https://github.com/varianter/variant.no/issues/606
- [ ] https://github.com/varianter/variant.no/issues/559
- [ ] https://github.com/varianter/variant.no/issues/608
- [ ] https://github.com/varianter/variant.no/issues/616
- [ ] https://github.com/varianter/variant.no/issues/619
```

**Comment by mikaelbr** [comment]
Avklaringer:

- Trenger ikke å implementere grafer i denne runden
- Det er OK med bare forrige års bonus.

**Comment by mathiazom** [comment]
WCAG krav avventes til design er klart
