### ISSUE TITLE
Legge til kalkulator-data i Compensations

### ISSUE THREAD

**Issue by anemne** [varianter/variant.no#543]
```[tasklist]
### Tasks
- [ ] https://github.com/varianter/variant.no/issues/523
- [ ] https://github.com/varianter/variant.no/issues/571
- [ ] https://github.com/varianter/variant.no/issues/588
```
