### ISSUE TITLE
Organiser og strukturer alt som er selskapsrelatert under dokumentet CompanyInfo.

### ISSUE THREAD

**Issue by anemne** [varianter/variant.no#545]
```[tasklist]
### Tasks
- [ ] https://github.com/varianter/variant.no/issues/548
- [ ] https://github.com/varianter/variant.no/issues/546
- [ ] https://github.com/varianter/variant.no/issues/554
- [ ] https://github.com/varianter/variant.no/issues/549
```
