### ISSUE TITLE
Ha en søkemotor-tilgjengelig nettside for økt synlighet

### ISSUE THREAD

**Issue by mathiazom** [varianter/variant.no#555]
## Bakgrunn og behov

For å kunne være godt synlig via søk, må vi legge tilrette for god crawling og indeksering fra tjenester. Innhold er som alltid viktigst, men for dette behovet tenker vi på innhold som separat oppgave. Dvs. vi trenger ikke vite hva innholdet skal være, men vi må legge tilrette for at SEO, crawling, preview fungerer bra.

Det er viktig å ta høyde for ulike løsninger som kan referere til innhold:
- Søkemotorer
- Sosiale medier (Linkedin, Facebook, Slack) via OpenGraph

Dersom innhold på siden har featured bilde, burde det vises som bilde til OpenGraph i rett utsnitt (1,200 x 630 px). Det burde være mulig å velge preview-bilde til OpenGraph via metadata i CMS.

Definisjon av Metadata burde være konsekvent på tvers av innhold, enten det er "pages", eller ting som bloggposter, nyheter, kalkulator, ansattoversikt, osv.

## Akseptansekriterier:
- [x] Sider skal være crawlable av søkemoterer.
- [x] Det skal være mulig å sette metadata via CMS som er spesifikk per innhold: tittel, description, keywords.
- [x] Dersom metadata ikke er satt på spesifikk innholdsside, skal det være en god default som vises i stedet.
- [x] Innholdssider lenket til via LinkedIn (et.al) skal vise egen definert innhold styrt fra CMS om tilgjengelig
- [x] Om ikke spesifikk innhold til OpenGraph er tilgjengelig skal standard-innhold vises.
- [x] Bilder til OpenGraph skal være 1,200 x 630 px
- [x] Skal ha tilgjengelig sitemap.xml

```[tasklist]
### Tasks
- [ ] https://github.com/varianter/variant.no/issues/579
- [ ] https://github.com/varianter/variant.no/issues/578
- [ ] https://github.com/varianter/variant.no/issues/561
- [ ] https://github.com/varianter/variant.no/issues/560
- [ ] https://github.com/varianter/variant.no/issues/573
- [ ] https://github.com/varianter/variant.no/issues/595
```

**Comment by mikaelbr** [comment]
Additionally, OpenGraph metadata should be set correctly and individually for each page.

Should also consider generating individual preview images for Open Graph. See example: https://github.com/varianter/handbook/blob/main/pages/api/og-search.tsx

**Comment by christinaroise** [comment]
For preview images, sanity is backing and contributing to this plugin: https://www.sanity.io/plugins/asset-source-ogimage and vercel has this as an option: https://vercel.com/docs/functions/og-image-generation

All pages have the SEO object added. It will and is added to new pages as we create them as schemas

**Comment by mathiazom** [comment]
> For preview images, sanity is backing and contributing to this plugin: https://www.sanity.io/plugins/asset-source-ogimage

That plugin does not work with Sanity Studio v3, and is no longer maintained. 

Here is a v3 fork we could use: https://www.sanity.io/plugins/og-image-generator-plugin

**Comment by mikaelbr** [comment]
But also, not all roads lead to Sanity. There are possible futures where sites and subsites exsists outside the realm of Sanity. So a solution generic as preview images I don't think needs to be tightly coupled to the CMS.

**Comment by mikaelbr** [comment]
I think this is a good general rule, to always consider "what should or needs to be part of the CMS", to avoid putting all our eggs into the Sanity basket just by deafult frame of mind

**Comment by mathiazom** [comment]
> Should also consider generating individual preview images for Open Graph. See example: https://github.com/varianter/handbook/blob/main/pages/api/og-search.tsx

What was the reason for not using `@vercel/og`, but just Satori directly? To support the Node runtime?

**Comment by mikaelbr** [comment]
In this case it was quick and dirty reuse of something that was running in a docker container (thus not edge as you imply). So that judgement call does not automatically apply to this case.

**Comment by mikaelbr** [comment]
Avhengig av språk. Scopes til senere

**Comment by mikaelbr** [comment]
https://v3.variant.no/sitemap.xml show wrongs URLs.

**Comment by mathiazom** [comment]
Should look into making the sitemap dynamic (generate per request, not at build)

https://github.com/iamvishnusankar/next-sitemap?tab=readme-ov-file#server-side-sitemap-getserversidesitemap

**Comment by mathiazom** [comment]
Sitemap has now been set to generate per request in order to keep the urls fresh. Since this is a fairly naive approach, an issue has been created to create a more performant solution: #650

**Comment by mathiazom** [comment]
Some bugs that need to be fixed: #693, #694
