### ISSUE TITLE
Lansering checklist

### ISSUE THREAD

**Issue by mikaelbr** [varianter/variant.no#962]
## Gjøremål før lansering
- [ ] Legge inn all Open Graph og Metadata på sider.
- [ ] Lage egne OG bilder til landingssidene (@sindreholm )
- [ ] Sjekk etter perf quick wins (@mikaelbr )
- [ ] Legge inn logging på brekte lenker
- [ ] Nytt favicon
- [ ] Fjerne eksempelcase på v3.variant.no (Ruter)

## Akseptansetester
- [ ] Alle sider fungerer på mobil.
- [ ] Alle sider fungerer på desktop (ulike sider).
- [ ] Alle lenker fungerer
- [ ] Verifisere tall i lønnskalkulator (@Krakels )
- [ ] Verifiser oversettelser (engelsk og norsk)
- [ ] Gå igjennom alle sider med tastaturnavigasjon
- [ ] Se at alle ansatte er på plass og alle tidligere ansatte ikke er på plass.
- [ ] Verifiser alle bilder
- [ ] Få case-produsenter (Linn Helen, Anders) til å verifisere case-sider
- [ ] Test i ulike nettlesere (Firefox, Safari, Chrome, Arc, Opera???)
- [ ] Verifiser sitemap
- [ ] Gjennomgang tekster.

## Lanseringssjekkliste

- [x] Alle må endre bilder
- [x] Endre DNS (@mikaelbr )
- [ ] Reindekser fra Search Console
- [ ] Rette opp døde lenker som blir oppdaget

## Til senere

- [ ] Innhold variant.se

**Comment by mikaelbr** [comment]
Denne er defacto ferdig pga tid
